version: '3'
services:
  console:
    build: .
    ports:
      - "5000:5000"
    links:
      - db 
  db:
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql